### ISSUE TITLE
Missing asset

### ISSUE THREAD

**Issue by quintonv** [shawyunz/XampleUI#1]
I just did a clone and tried to build, there's a compile error 
CSC : error CS1566: Error reading resource 'XampleUI.Assest.Gilroy-ExtraBold.otf' -- 'Could not find file 'XampleUI-main\XampleUI\XampleUI\Assest\Gilroy-ExtraBold.otf'.'

**Comment by shawyunz** [comment]
Hi quintonv,

Please comment out or remove the font in "AssemblyInfo.cs".
And the FontFamiliy lines in CakeList.xaml and CakeDetail.xaml as below for now.
![image](https://user-images.githubusercontent.com/43285754/98184273-d5dfa700-1f6e-11eb-8b60-7a1260f02ba0.png)

I searched the font by the image and find those similar ones.
However, as those two are not free for app distributions, otf files are not uploaded.
I'll check the appearance without that particular font and update to the repo later.

Cheers.

**Comment by quintonv** [comment]
Thanks for the fix :)
